"use client";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { MapPin, Search, Star, ShieldCheck, Clock3, ArrowRight, Wind, Sparkles, Wrench, Zap, Scissors, Shield } from "lucide-react";
import API from "@/api/api";
const icons: Record<string, React.ElementType> = { Wind, Sparkles, Wrench, Zap, Scissors, Shield };
export default function Home() {
  const {data,isLoading,error}=useQuery({queryKey:["home"],queryFn:async()=>(await API.get("/home")).data,retry:false});if(isLoading)return <div className="loading">Loading HomeServe+ services…</div>;if(error||!data)return <div className="api-error"><h2>Marketplace data unavailable</h2><p>Start the API and MongoDB, then refresh this page.</p></div>;
  return <main>
    <header className="nav"><Link href="/" className="brand">HomeServe<span>+</span></Link><nav><Link href="/services">Services</Link><Link href="#professionals">Why us</Link><Link href="/professional">Work as a professional</Link><Link href="/login" className="nav-login">Log in</Link><Link href="/signup" className="pill">Join now</Link></nav></header>
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><ShieldCheck size={17}/> Trusted professionals. Transparent prices.</div><h1>Your home deserves <em>expert care.</em></h1><p>Book verified professionals for cleaning, repairs and everyday home services—when and where you need them.</p><div className="searchbox"><div><MapPin/><span>Kolkata</span></div><label><Search/><input placeholder="What service do you need?"/></label><Link href="/services">Search</Link></div><div className="trust"><span><b>{data.stats.averageRating||"New"}</b> customer rating</span><span><b>{data.stats.completedBookings}</b> completed services</span><span><b>{data.stats.verifiedProfessionals}</b> verified experts</span></div></div><div className="hero-art"><div className="art-card"><div className="art-icon"><Sparkles/></div><h3>Expert care,<br/>right at your door.</h3><div className="floating-rating"><Star fill="currentColor"/> {data.stats.averageRating||"New"} <small>Live rating</small></div><div className="floating-safe"><ShieldCheck/> Verified professionals</div></div></div></section>
    <section className="section"><div className="section-title"><div><span>EVERYDAY ESSENTIALS</span><h2>What can we help with?</h2></div><Link href="/services">View all services <ArrowRight size={17}/></Link></div><div className="category-grid">{data.categories.map((c:any)=>{const Icon=icons[c.icon]||Wrench; return <Link href={`/services?category=${c._id}`} className="category" key={c._id}><i><Icon/></i><b>{c.name}</b><small>Book now <ArrowRight size={13}/></small></Link>})}</div></section>
    <section className="section soft"><div className="section-title"><div><span>MOST LOVED</span><h2>Popular services near you</h2></div></div><div className="service-grid">{data.services.map((s:any,i:number)=><Link href={`/services/${s.slug}`} className="service-card" key={s._id}><div className={`service-image tone-${i%3}`}><span>{i===0?"AC Care":i===1?"Deep Clean":"Quick Fix"}</span></div><div className="service-body"><div className="rating"><Star size={14} fill="currentColor"/> {s.rating || 4.8}</div><h3>{s.name}</h3><p>{s.description}</p><footer><div><del>₹{s.price}</del><strong>₹{s.discountedPrice||s.price}</strong></div><span>Book <ArrowRight size={14}/></span></footer></div></Link>)}</div></section>
    <section className="why"><div><span>WHY HOMESERVE+</span><h2>Good help should<br/>never be hard to find.</h2></div><div className="why-grid"><article><ShieldCheck/><h3>Verified experts</h3><p>Every professional is identity and skill verified.</p></article><article><Clock3/><h3>On-time service</h3><p>Choose a convenient time and track every update.</p></article><article><Star/><h3>Quality guaranteed</h3><p>Transparent reviews and a service warranty.</p></article></div></section>
    <section className="professional-cta"><div><small>FOR SERVICE PROFESSIONALS</small><h2>Skilled at what you do?<br/>Build your career with us.</h2><p>Choose your services and schedule, get matched with nearby customers, and manage your earnings in one place. Every professional is reviewed before joining the marketplace.</p><div><span><ShieldCheck/> Verified profile</span><span><Clock3/> Flexible hours</span><span><Star/> Grow your reputation</span></div><Link href="/professional">Start professional registration <ArrowRight/></Link></div><aside><b>01</b><p>Create your account and professional profile</p><b>02</b><p>Upload identity and skill documents</p><b>03</b><p>Get approved by HomeServe+ Admin</p></aside></section>
    <footer className="footer"><b className="brand">HomeServe<span>+</span></b><p>Expert care for every corner of your home.</p><small>© 2026 HomeServe+. All rights reserved.</small></footer>
  </main>;
}
